FROM invent-registry.kde.org/sysadmin/ci-images/sles15-craft@sha256:a1d8f5683230defd69a7c7fbdd0e185c98307bdf6d314131da30ec63c3527fe0

# using a non root user doesn't work with drone 💖
# https://stackoverflow.com/a/50613378
USER root


RUN zypper --non-interactive update && \
    zypper --non-interactive install \
    # rpm
    popt-devel file-devel \
    # dpkg
    libmd-devel  ncurses-devel \
    && \
    # cleanup to ensure we don't leave behind anything that doesn't need to be in the image
    zypper --non-interactive clean -a

# the code is checked out on the host so the user will be different
RUN git config --system --add safe.directory '*'
