FROM invent-registry.kde.org/sysadmin/ci-images/sles15-craft@sha256:b4734f262aa2298f79ae20c7166199549477d2a832488ef98b3ac38ffefe5fd8

# using a non root user doesn't work with drone 💖
# https://stackoverflow.com/a/50613378
USER root


RUN zypper --non-interactive update && \
    zypper --non-interactive install \
    # rpm
    popt-devel file-devel \
    # dpkg
    libmd-devel  ncurses-devel \
    && \
    # cleanup to ensure we don't leave behind anything that doesn't need to be in the image
    zypper --non-interactive clean -a

RUN zypper --non-interactive install bzip2 && \
    curl -q http://zsync.moria.org.uk/download/zsync-0.6.2.tar.bz2 | tar -xj && \
    cd zsync-0.6.2/ && \
    ./configure --prefix=/usr/local && \
    make -j4 install && \
    cd .. && \
    rm -r zsync-0.6.2/
