FROM invent-registry.kde.org/sysadmin/ci-images/sles15-craft@sha256:973215a5b49b3f7f9ba55f99717070d77dfd3021123c1b24aa763b46c5b13f27

# using a non root user doesn't work with drone 💖
# https://stackoverflow.com/a/50613378
USER root


RUN zypper --non-interactive update && \
    zypper --non-interactive install \
    # rpm
    popt-devel file-devel \
    # dpkg
    libmd-devel  ncurses-devel \
    && \
    # cleanup to ensure we don't leave behind anything that doesn't need to be in the image
    zypper --non-interactive clean -a

# the code is checked out on the host so the user will be different
RUN git config --system --add safe.directory '*'
